{
 "title": "Alerts",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "HTTP 5xx Codes",
   "type": "timeseries",
   "description": "HTTP Codes 500 - 599",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service,code) (http_request_duration_seconds_count{code=~\"5.*\"})",
     "legendFormat": "{{service}}=>{{code}}"
    }
   ]
  },
  {
   "title": "Kubernetes Pod Running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", pod!~\"tiller-deploy-.*|grafana-deployment-.*|prometheus-monitoring-.*\"})",
     "legendFormat": "Pods Running"
    }
   ]
  },
  {
   "title": "Kubernetes Pod Failed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase=\"Failed\", pod!~\"tiller-deploy-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kubernetes Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(container) (kube_pod_container_status_restarts_total{pod!~\"tiller-deploy-.*\"})",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}