{
 "title": "Backend Business KPIs",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests Services",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service, namespace, code) (http_request_duration_seconds_bucket{endpoint!=\"/healthz\"} - http_request_duration_seconds_bucket{endpoint!=\"/healthz\"} offset 1m)",
     "legendFormat": "{{service}}@{{namespace}}:{{code}}"
    }
   ]
  },
  {
   "title": "HTTP Duration Services",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (service, namespace, path) (http_request_duration_seconds_sum{endpoint!=\"/healthz\"} / http_request_duration_seconds_sum{endpoint!=\"/healthz\"})",
     "legendFormat": "{{service}}@{{namespace}}:{{path}}"
    }
   ]
  },
  {
   "title": "Number Of Pods",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count by(app) (kube_pod_status_phase{phase=\"Running\", pod=~\"frontendchart.*\"})",
     "legendFormat": "{{app}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Number Of Pods",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count by (service) (kube_pod_status_phase{phase=\"Running\", pod=~\"mongodb.*\"})",
     "legendFormat": "{{app}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Number Of Pods",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count by(app) (kube_pod_status_phase{phase=\"Running\", pod=~\"backendchart.*\"})",
     "legendFormat": "{{app}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "backend http 200",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (http_requests_received_total{code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_request_duration_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (action) (http_request_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_requests_in_progress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (container) (http_requests_in_progress)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_request_duration_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller) (http_request_duration_seconds_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_request_duration_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (code) (http_request_duration_seconds_bucket)"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{pod}}@{{namespace}}" }
   ]
  },
  {
   "title": "Go Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{pod}}@{{namespace}}" }
   ]
  }
 ]
}