{
 "title": "HTTP Errors Details",
 "description": "Monitor HTTP Request ERRROR with information about Error sources",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Error   5xx & 429 ",
   "type": "bargauge",
   "description": "General Error Elasticproxy \nHTTP Status Code 5xx, 429",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code)(http_requests_received_total{code=~\"(5..|429)\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time ",
   "type": "timeseries",
   "description": "Response Time",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_sum{code!=\"\"}[$__interval]) / irate(http_request_duration_seconds_count{code!=\"\"}[$__interval])) by (endpoint)",
     "legendFormat": "{{upstream_status}}"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Backend HTTP 5xx & 429",
   "type": "timeseries",
   "description": "Backend  HTTP 5xx & 429",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (code,endpoint)(http_requests_received_total{code=~\"(5..|429)\",endpoint!=\"\"})",
     "legendFormat": "{{code}}:{{endpoint}}"
    }
   ]
  },
  {
   "title": "Response Time Backend",
   "type": "timeseries",
   "description": "Response Time Backend",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_sum{code!=\"\"}[$__interval]) / irate(http_request_duration_seconds_count{code!=\"\"}[$__interval])) by (endpoint,code)",
     "legendFormat": "{{code}}:{{endpoint}}"
    }
   ]
  }
 ]
}