{
 "title": "HTTP Errors Details",
 "description": "Monitor HTTP Request ERRROR with information about Error sources",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Error   5xx & 429 Elasticproxy",
   "type": "bargauge",
   "description": "General Error Elasticproxy \nHTTP Status Code 5xx, 429",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (upstream_status)(nginx_status{job=\"elasticproxy\",upstream_status=~\"(5..|429)\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time Elasticproxy ",
   "type": "timeseries",
   "description": "Response Time Elasticproxy ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(nginx_status{service=\"elasticproxy\"}[$__interval])) by (upstream_status)",
     "legendFormat": "{{upstream_status}}"
    }
   ]
  },
  {
   "title": "BKMO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "BKMO HTTP 5xx & 429",
     "type": "timeseries",
     "description": "BKMO HTTP 5xx & 429",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (upstream_status,uri)(nginx_status{job=\"elasticproxy\",upstream_status=~\"(5..|429)\",uri=~\"/ui.*\"})",
       "legendFormat": "{{upstream_status}}:{{uri}}"
      }
     ]
    },
    {
     "title": "Response Time BKMO",
     "type": "timeseries",
     "description": "Response Time BKMO",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(irate(nginx_status{service=\"elasticproxy\",uri=~\"/ui.*\"}[$__interval])) by (upstream_status,uri)",
       "legendFormat": "{{upstream_status}}:{{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BKMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "BKMP HTTP 5xx & 429",
     "type": "timeseries",
     "description": "BKMP HTTP 5xx & 429",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by (upstream_status,uri)(nginx_status{job=\"elasticproxy\",upstream_status=~\"(5..|429)\",uri=~\"/bkmp.*\"})",
       "legendFormat": "{{upstream_status}}:{{uri}}"
      }
     ]
    },
    {
     "title": "Response Time BKMP",
     "type": "timeseries",
     "description": "Response Time BKMP",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(irate(nginx_status{service=\"elasticproxy\",uri=~\"/bkmp.*\"}[$__interval])) by (upstream_status,uri)",
       "legendFormat": "{{upstream_status}}:{{uri}}"
      }
     ]
    }
   ]
  },
  { "title": "API-GATEWAY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "API-GATEWAY HTTP 5xx & 429",
   "type": "timeseries",
   "description": "API-GATEWAY HTTP 5xx & 429",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (upstream_status,uri)(nginx_status{job=\"elasticproxy\",upstream_status=~\"(5..|429)\",uri=~\"/oauth2.*\"})",
     "legendFormat": "{{upstream_status}}:{{uri}}"
    }
   ]
  },
  {
   "title": "Response Time API-GATEWAY ",
   "type": "timeseries",
   "description": "Response Time API-GATEWAY ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(irate(nginx_status{service=\"elasticproxy\",uri=~\"/oauth2.*\"}[$__interval])) by (upstream_status,uri)",
     "legendFormat": "{{upstream_status}}:{{uri}}"
    }
   ]
  },
  { "title": "ID-BROKER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "ID-BROKER HTTP 5xx & 429",
   "type": "timeseries",
   "description": "ID-BROKER HTTP 5xx & 429",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (upstream_status,uri)(nginx_status{job=\"elasticproxy\",upstream_status=~\"(5..|429)\",uri=~\"/auth.*\"})",
     "legendFormat": "{{upstream_status}}:{{uri}}"
    }
   ]
  },
  {
   "title": "Response Time ID-BROKER",
   "type": "timeseries",
   "description": "Response Time ID-BROKER",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(irate(nginx_status{service=\"elasticproxy\",uri=~\"/auth.*\"}[$__interval])) by (upstream_status,uri)",
     "legendFormat": "{{upstream_status}}:{{uri}}"
    }
   ]
  },
  { "title": "BKMK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "BKMK HTTP 5xx & 429",
   "type": "timeseries",
   "description": "BKMK HTTP 5xx & 429",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (upstream_status,uri)(nginx_status{job=\"elasticproxy\",upstream_status=~\"(5..|429)\",uri=~\"/api.*\"})",
     "legendFormat": "{{upstream_status}}:{{uri}}"
    }
   ]
  },
  {
   "title": "BKMK HTTP 5xx & 429",
   "type": "timeseries",
   "description": "BKMK HTTP 5xx & 429",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum(irate(nginx_status{service=\"elasticproxy\",uri=~\"/api.*\"}[$__interval])) by (upstream_status,uri)",
     "legendFormat": "{{upstream_status}}->{{uri}}"
    }
   ]
  }
 ]
}