{
 "title": "Status Page",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Identity Pods",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (app) (ds_service_http_duration_seconds_count{service=\"data-identity-service\", path=\"/v1/health\"})"
    }
   ]
  },
  {
   "title": "reverse-proxy Pods",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (service) (kube_pod_status_phase{phase=\"Running\",pod=~\"reverse-proxy.*\"})"
    }
   ]
  },
  {
   "title": "Application Status Identity",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "count by (service, namespace) (ds_service_http_duration_seconds_count{path=\"/v1/health\", service=\"data-identity-service\"})",
     "legendFormat": "{{service}}@{{namespace}}"
    }
   ]
  },
  {
   "title": "Application Status reverse-proxy",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "count by (service, namespace) (kube_pod_status_phase{phase=\"Running\",pod=~\"reverse-proxy.*\"})",
     "legendFormat": "reverse-proxy@{{namespace}}"
    }
   ]
  }
 ]
}